package Assignment2.BadSmells;

/*
 * Smell: Divergent Change
 *
 * Original problem:
 * One class held three completely unrelated concerns: report formatting,
 * SQL generation, and CSV export. A change to the report layout, a database
 * migration, or a new CSV dialect would all land on the same class for
 * different reasons — the definition of Divergent Change.
 *
 * Refactorings applied:
 * - Extract Class: three focused classes replace the one bloated class.
 *   ExamReportFormatter owns report title/footer.
 *   ExamResultSqlBuilder  owns table name and database URL.
 *   ExamResultCsvExporter owns separator and header flag.
 * - Move Method + Move Field: each field and method moved to the class
 *   that changes for the same reason.
 *
 * Why it is better:
 * A change to the report format touches only ExamReportFormatter.
 * A schema migration touches only ExamResultSqlBuilder.
 * A CSV dialect change touches only ExamResultCsvExporter.
 * No class has more than one reason to change.
 */
public class DivergentChangeExample {

    static class ExamReportFormatter {
        private final String title  = "Exam Results";
        private final String footer = "Generated by registrar office";

        public String formatStudentReport(String name, int score) {
            return title + "\n" + name + ": " + score + "\n" + footer;
        }
    }

    static class ExamResultSqlBuilder {
        private final String tableName   = "exam_results";
        private final String databaseUrl = "jdbc:mysql://localhost:3306/school";

        public String buildSqlInsert(String name, int score) {
            return "/* " + databaseUrl + " */ INSERT INTO " + tableName
                 + "(name, score) VALUES ('" + name + "', " + score + ")";
        }
    }

    static class ExamResultCsvExporter {
        private final String  csvSeparator     = ",";
        private final boolean includeCsvHeader = true;

        public String exportCsv(String name, int score) {
            String row = name + csvSeparator + score;
            if (includeCsvHeader) {
                return "name" + csvSeparator + "score\n" + row;
            }
            return row;
        }
    }

    public void clientCode() {
        ExamReportFormatter  formatter = new ExamReportFormatter();
        ExamResultSqlBuilder builder   = new ExamResultSqlBuilder();
        ExamResultCsvExporter exporter = new ExamResultCsvExporter();

        System.out.println(formatter.formatStudentReport("Nino", 95));
        System.out.println(builder.buildSqlInsert("Nino", 95));
        System.out.println(exporter.exportCsv("Nino", 95));
    }
}
